name: spotube
description: A lightweight free Spotify crossplatform-client which handles playback manually, streams music using Youtube & no Spotify premium account is needed

publish_to: "none"

version: 2.4.1+14

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  cached_network_image: ^3.2.2
  html: ^0.15.0
  http: ^0.13.4
  shared_preferences: ^2.0.11
  spotify: ^0.8.0
  url_launcher: ^6.1.5
  youtube_explode_dart: ^1.10.8
  bitsdojo_window: ^0.1.5
  path: ^1.8.0
  path_provider: ^2.0.8
  collection: ^1.15.0
  flutter_riverpod: ^1.0.3
  flutter_hooks: ^0.18.2+1
  hooks_riverpod: ^1.0.3
  go_router: ^3.0.4
  palette_generator: ^0.3.3
  logger: ^1.1.0
  permission_handler: ^10.0.1
  marquee: ^2.2.3
  scroll_to_index: ^2.1.1
  package_info_plus: ^1.4.3
  version: ^3.0.2
  audio_service: ^0.18.7
  hookified_infinite_scroll_pagination: ^0.1.0
  skeleton_text: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dbus: ^0.7.3
  audioplayers:
    git:
      url: https://github.com/bluefireteam/audioplayers.git
      ref: 3ee12cd0361c0fc2f3d0303c504732d12fa8e49a
      path: packages/audioplayers/
  introduction_screen: ^3.0.2
  audio_session: ^0.1.10
  file_picker: ^5.2.0
  popover: ^0.2.6+3
  queue: ^3.1.0+1
  auto_size_text: ^3.0.0
  badges: ^2.0.3
  mime: ^1.0.2
  metadata_god: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.10.0
  hive_generator: ^1.1.3
  build_runner: ^2.2.1
  flutter_distributor: ^0.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/tutorial/

flutter_icons:
  android: true
  image_path: "assets/spotube-logo.png"
  adaptive_icon_foreground: "assets/spotube-logo-foreground.jpg"
  adaptive_icon_background: "#ffffff"
